name: Update GitHub Contribution Grid Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        run: |
          npx snk --username msarayu20 --theme purple --output ./github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./github-contribution-grid-snake.svg
          git commit -m "Update contribution grid (Automated)"
          git push origin main
